#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Sep 04, 2022 03:43:25 PM +03  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
from tkinter.filedialog import askopenfilename


import Renamer

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = Renamer.Toplevel1(_top1)
    root.mainloop()

def Buton_onizle(*args):
    print('Renamer1_2_support.Buton_onizle')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def Uygula(*args):
    print('Renamer1_2_support.Uygula')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def cikar(*args):
    print('Renamer1_2_support.cikar')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def ekle(*args):
    secim = askopenfilename()
    return secim

if __name__ == '__main__':
    Renamer.start_up()




