#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Jul 04, 2022 09:17:22 PM +03  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
from tkinter import filedialog as fd
from tkinter.messagebox import showinfo

import Renamer

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = Renamer.Toplevel1(_top1)
    root.mainloop()

def Onizle(*args):
    print('Renamer_support.Onizle')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def Uygula(*args):
    print('Renamer_support.Uygula')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

# def dosya_sec(*args):
#     print('Renamer_support.dosya_sec')
#     for arg in args:
#         print ('another arg:', arg)
#     sys.stdout.flush()

def dosya_sec():
    filetypes = (
        ('PDF Dosyaları', '*.pdf'),
        ('Ofis Dosyaları', '*.docx'),
        ('Ofis Dosyaları', '*.xlsx'),
        ('Görüntü Dosyaları', '*.png'),
        ('Görüntü Dosyaları', '*.jpg'),
        ('Görüntü Dosyaları', '*.jpeg'),
        ('Görüntü Dosyaları', '*.gif'),
        ('All files', '*.*')
    )

    filenames = fd.askopenfilenames(
        title='Yeniden adlandırılacak dosyaları seçin',
        initialdir='/',
        filetypes=filetypes)

    dosyalar = list(filenames)
    for i in dosyalar:
        print(i)
        
    return dosyalar
    

    # showinfo(
    #     title='Selected Files',
    #     message=filenames
    # )



if __name__ == '__main__':
    Renamer.start_up()




